### ISSUE TITLE
Remove local execution of bash scripts

### ISSUE THREAD

**Issue by jstaf** [vmfarms/terraform-kubernetes-basic-auth#3] opened 2020-02-28 20:02 UTC
Instead of using program to execute htpasswd locally, I believe we can use built-in terraform functions to generated the same htpasswd hash used for basic auth.

**Comment by kostecky** [comment] 2020-03-02 14:36
Duplicate of https://github.com/vmfarms/terraform-kubernetes-basic-auth/issues/3

**Closed by kostecky** 2020-03-02 14:36 UTC
